### ISSUE TITLE
Plotting Density objects is very slow

### ISSUE THREAD

**Issue by dill** [DistanceDevelopment/DSsim#14]
Playing around with plotting a density surface in `DSsim`, I noticed that plotting a density takes a long time. Profiling the code, it seems like this is down to [this chunk of code](https://github.com/LHMarshall/DSsim/blob/master/DSsim/R/Density.R#L167:L174) where there is a look-up for cells to squish them into the grid. The repeated calls to `which()` are particularly problematic, especially with larger grids.

I'd try storing the density (i.e., the `...@population.description@density` object) as a `matrix` for the values and then the corresponding coordinates as vectors (`x` and `y`), then you could use something like

``` r
dat <- expand.grid(x=x, y=y)
dat$denisty <- as.vector(density.matrix)
```

(provided you keep everything in the right order).

Expanding stuff out should be more efficient than doing the lookup. Of course there are a number of other options to get around this slowness, this was just the first one that came to mind.

**Comment by LHMarshall** [comment]
Not something I will work on now in DSsim, this has a different implementation in dsims and uses ggplot
