### ISSUE TITLE
Plot methods are not exported properly

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/DSsim#18]
The plot methods do not appear to be exported properly. They are not available from within other function calls.

@dill you were struggling with this too... think I just found the fix!

**Comment by dill** [comment]
Thanks @LHMarshall, I'll take this for a spin next time I'm working with `DSsim`.

**Comment by LHMarshall** [comment]
@dill download it from my 1.0.8 pre release when you need it
