### ISSUE TITLE
Add simple simulation defaults

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/DSsim#23]
So that users can run a simple simulation just from the package defaults.

**Comment by LHMarshall** [comment]
Now has basic defaults so that a simulation can be run without providing any arguments (except currently need to specify point as have not implemeted line transect generation yet... coming soon!). 

A simulation can now be created, "viewed", run and summarised using 4 lines of code:

```
library(DSsim)
sim <- make.simulation(design.obj = make.design("point"))
check.sim.setup(sim)
sim <- run(sim) #Note default is to run it 100 times
summary(sim)
```

![defaultpointexample](https://cloud.githubusercontent.com/assets/1295691/20063252/601cbd44-a4fe-11e6-826a-75f66ac9f097.jpeg)

**Comment by erex** [comment]
Default number of replicates (specified by `make.simulation()`) is 10, not 100

**Comment by LHMarshall** [comment]
@erex yes I changed my mind thought 100 was too high by default.... happy for suggestions...

**Comment by erex** [comment]
quick execution is important for the punters; 10 reps is fine.

**Comment by LHMarshall** [comment]
```
library(DSsim)
sim <- make.simulation()
check.sim.setup(sim)
```

Now yields:
![screen shot 2016-11-10 at 12 54 32](https://cloud.githubusercontent.com/assets/1295691/20177515/1a6bf4c4-a745-11e6-9db7-950863b00663.png)
