### ISSUE TITLE
Get DSsim to generate simple systematic line transect design

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/DSsim#24]
This will form one of the defaults for issue #23 (at the moment the user needs to generate a shapefile for the transects from Distance so this makes DSsim rather complicated to get started with)

Dave has some code to do this I think

Plan is to initially stick to a design axis of 0 and a systematic spacing with random start point.

**Comment by LHMarshall** [comment]
@dill did you have some code that does this? If so could we chat briefly sometime? Cheers

**Comment by dill** [comment]
I don't have code for transect generation. All the work I did with DSsim 
is in

https://github.com/dill/spatlaugh/

and

https://github.com/dill/ltdesigntester

An example of how things work is in:

https://github.com/dill/spatlaugh/blob/master/simulation_study/driver.R

(sorry this isn't terribly well organised at the moment)

**Comment by LHMarshall** [comment]
Using rgeos for clipping

![screen shot 2016-11-10 at 11 04 31](https://cloud.githubusercontent.com/assets/1295691/20174401/8dd28988-a735-11e6-83f6-28ba21c80b69.png)
