### ISSUE TITLE
Include basic individual level covariates in simulations

### ISSUE THREAD

**Issue by LHMarshall** [DistanceDevelopment/DSsim#26]
Include individual level covariates like, sex, colour... in the population description, detectability and analyses

**Comment by erex** [comment]
I think of those as "individual" level covariates, rather than population leve.

**Comment by LHMarshall** [comment]
@erex I did wonder as I was writing it.

**Comment by LHMarshall** [comment]
@erex @lenthomas @dill 

Thought please... the user inputs the scale parameter directly as the value of sigma in the half normal. Should the covariate parameters be supplied on the same scale (then I log everything inside DSsim)? or the log scale?

**Comment by erex** [comment]
I would suspect users will be thinking on the biological scale rather than on the log scale.  Let the software do the conversion for them.

**Comment by dill** [comment]
@erex I agree for non-covariate models, but not sure about interpreting "response" (i.e., exponentiated) scale effects for covariates (since they're multiplicative not additive on that scale?) -- I think this gets tricky to think about. This also goes against how we specify starting values in `Distance` and `mrds`...

I would suggest log scale but with some quick plottig to show what different combinations look like (each level of each factor and 0.25, 0.5, 0.75 quantiles of continuous covars), so folks can see what could go wrong?

Regardless of the log/exp thing, I find myself making a lot of plots when I do these simulations to make sure that the ESW is right, easy plotting seems helpful.

**Comment by LHMarshall** [comment]
@dill got any plotting code for that then? :)

**Comment by dill** [comment]
mmds has the maths for the more complicated case of mixture model 
detection functions, but they are not standard mrds objects. Might be 
useful anyway.

**Comment by LHMarshall** [comment]
Hmm also log(0) and log of negative values is problematic! Another reason to use log scale...

**Comment by erex** [comment]
I think using the specification of starting values as a template for how users will specify covariates is not helpful.

Someone using the software would be more likely to be able to answer the question: 
at half the truncation distance, how much more likely are males to be detected than females?

Seems the programmers' task is to convert that into betas.

Consult our [old friend WiSP](https://github.com/DistanceDevelopment/WiSP/blob/master/man/setpars.survey.lt.Rd) for ideas of how this problem was tackled previously.  Not saying that was the perfect solution, but there is a wheel re-invention happening here.

**Comment by dill** [comment]
On 21/11/2016 10:57, erex wrote:

> I think using the specification of starting values as a template for how
> users will specify covariates is not helpful.

Agree BUT these are also on the scale returned by summary() etc. 
Comparing what you put in with what you get out is annoying when you 
have to shift scales; better if they are the same even if the scale is 
"unnatural".

> Someone using the software would be more likely to be able to answer the
> question:
> at half the truncation distance, how much more likely are males to be
> detected than females?
> 
> Seems the programmers' task is to convert that into betas.
> 
> Consult our old friend WiSP
> https://github.com/DistanceDevelopment/WiSP/blob/master/man/setpars.survey.lt.Rd
> for ideas of how this problem was tackled previously. Not saying that
> was the perfect solution, but there is a wheel re-invention happening here.

I think this is good but this formulation (back-conversion from min/max) 
only works for one covariate. Maybe this makes sense for the first shot 
at getting this to work. Not sure if we have the case of more than one 
individual-specific covariate often (as opposed to group size or weather 
conditions) -- I can think of sex, age class, behavioural state but 
perhaps it's uncommon to have all of these?

**Comment by LHMarshall** [comment]
Here is an example: females are harder to detect than males
  
  - sigma for males: 25
  - on the log scale my covariate adjustment parameter for females is negative -0.5 (i.e. the scale parameter gets smaller the detection function drops off quicker) but if the user were to have to input not on the log scale wouldn't the parameter be positive? exp(-0.5) = 0.606? That is really confusing for biologists I would have thought.

Surely explaining in the documentation the additive formula on the log scale is actually more intuitive, like it is in the Distance Sampling books?

**Comment by erex** [comment]
Find a biologist and ask them the more natural way to describe females being harder to detect than males.  Debates among statisticians garners less-than-perfect information on the subject.

Gui would be a reasonable guinea pig.

Our "poster child" publication on covariates is [Marques et al. (2007)](https://www.researchgate.net/publication/230766140_Improving_estimates_of_bird_density_using_multiple_covariate_distance_sampling).  It was published without an estimate of a $\beta$ anywhere.  Eqn. 5 is provided, but I doubt that is helpful.  The caption to Figure 2a takes a curious approach to the issue of covariates.

**Comment by LHMarshall** [comment]
Biologist Natacha says log scale... also she pointed out where would the covariate parameters be coming from... probably previously fitted detection functions which would be displaying the estimates on the log scale all ready to be passed in to DSsim.

Also Len happy with log scale.

**Comment by LHMarshall** [comment]
Adding a plotting function for covariates

```
# Make a multi strata region
poly1 <- data.frame(x = c(0,0,100,100,0), y = c(0,100,100,0,0))
poly2 <- data.frame(x = c(200,200,300,300,200), y = c(10,110,110,10,10))
coords <- list(list(poly1), list(poly2))
region <- make.region(coords = coords)
density <- make.density(region)

# Set up covariates
covariate.list <- list()
covariate.list$sex <- list(data.frame(level = c("male", "female"), prob = c(0.5,0.5)),
                           data.frame(level = c("male", "female"), prob = c(0.5,0.5)))
# Create covariate description
pop.desc <- make.population.description(region.obj = region, density.obj = density, covariates = covariate.list, N = c(200,200))

# define covariate parameters
cov.params <- list(sex = data.frame(level = c("male", "female","male", "female"),
                                    strata = c("A", "A", "B", "B"),
                                    param = c(0, -0.9, -0.2, -1.1)))
detect <- make.detectability(scale.param = 25,  cov.param = cov.params)

plot(detect, pop.desc)
```

![screen shot 2016-11-30 at 14 29 51](https://cloud.githubusercontent.com/assets/1295691/20756202/af2579ae-b709-11e6-93b7-7a8f6b7a727d.png)

**Comment by LHMarshall** [comment]
Comments on plots please... I wonder if there is an intelligent way to do legend placement? Are the labels clear? Need to keep them concise! The strata are called A and B in this example. I could add an option to omit legends.
@erex @dill @lenthomas 

![screen shot 2016-11-30 at 21 47 01](https://cloud.githubusercontent.com/assets/1295691/20772788/bfaa8bec-b746-11e6-96c1-fe2653c383ec.png)

**Comment by lenthomas** [comment]
@lauram Look good to me; not sure why the bottom one doesn't have 95%CI 
- must be missing something.  Don't know how to do smart legend 
placement -- but I bet there's some way to do it in R!


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by LHMarshall** [comment]
@lenthomas the bottom one is a factor covariate (so one line for males and one for females for each strata).... hmm guess this isn't clear from the legend then?

**Comment by dill** [comment]
Maybe have the title be "Covariate" or "Factor covariate" depending on 
the context?

I also have no idea how to do smart legend placement. I think there's 
some way to place the legend outside the plot, so it always has space 
but so much of these plots are whitespace anyway, it seems like a waste 
to do that...

**Comment by LHMarshall** [comment]
@dill thanks for suggestion. I have ammended the title also I have changed the lty settings so non are solid so the lines look a bit different to those on the other covariate plots.

If there are no more suggestions I will close this issue.

![screen shot 2016-12-06 at 12 06 06](https://cloud.githubusercontent.com/assets/1295691/20925073/8e9f9032-bbac-11e6-9594-5507b3ca6086.png)

**Comment by LHMarshall** [comment]
For no covariates but detection functions that vary by strata the plots are as follows:

```
pop.desc <- make.population.description(region.obj = region, density.obj = density, N = c(10,10))
detect <- make.detectability("hr", scale.param = c(25,28), shape.param = c(2,5))
plot(detect, pop.desc)
```
![screen shot 2016-12-06 at 12 18 56](https://cloud.githubusercontent.com/assets/1295691/20925339/4ac7f53c-bbae-11e6-840b-49d48c5556f4.png)

**Comment by LHMarshall** [comment]
If there are strata they will always be included in the legend

![screen shot 2016-12-06 at 15 36 12](https://cloud.githubusercontent.com/assets/1295691/20931693/d1b3efea-bbc9-11e6-8489-30874c75f70a.png)
