### ISSUE TITLE
Simulating size bias

### ISSUE THREAD

**Issue by erex** [DistanceDevelopment/DSsim#50]
@LHMarshall 

In anticipation of next week's size bias comments, I'm trying to simulate by making size a covariate in the detection function, see code below.  As I understand, the `covar.params` specifies the strength of the size effect.

```
library(DSsim)
library(Distance)
set.seed(2232)
eg.region <- make.region()
covariate.list <- list()
covariate.list$size <- list(list("ztruncpois", list(mean = 10)))
pop.desc <- make.population.description(covariates = covariate.list, N=200)
cov.params <- list(size = c(0.10))
detect <- make.detectability(scale.param = 10, 
                             cov.param = cov.params, 
                             truncation = 60)
plot(detect, pop.desc)
bob <- generate.population(pop.desc, detect, eg.region)

transects <- make.design()
simulation <- make.simulation()
thelines <- generate.transects(simulation)

fred <- make.simulation(reps=2, region=eg.region, design=transects, pop=pop.desc, det=detect,
                        ddf.analyses.list=make.ddf.analysis.list())
survey.design <- create.survey.results(fred, dht.tables = TRUE)

my.survey <- data.for.distance(object = survey.design)
scatter.smooth(my.survey$distance, my.survey$size)
summary(my.survey$size)
```

I do get a diagnostic plot of `size ~ distance` that suggests small groups are missed at large distances.  However, when I look at mean group size in the sample (using the `summary()` in the last statement of the code, I find it corresponds well with the presumed mean group size in the simulated population (10).

Why is the group size in the sample not considerably different than the group size in the population?  My limited experiments suggest that changing the size of the coefficient in `covar.params` does not seem to alter the mean group size in the sample as I would expect.

Given that mean size of the sample is roughly the same as mean in the population, I'm not inducing size bias via this simulation.  How is that accomplished?

**Comment by LHMarshall** [comment]
@erex I think the cluster size values are too similar and the parameters are just too weak to show a strong size bias effect... I made the parameters more extreme and the numbers looked more convincing:

```
cov.params <- list(size = c(0.3))
detect <- make.detectability(scale.param = 1, 
                             cov.param = cov.params, 
                             truncation = 60)
plot(detect, pop.desc)
bob <- generate.population(pop.desc, detect, eg.region)

transects <- make.design()
#simulation <- make.simulation()
#thelines <- generate.transects(simulation)

fred <- make.simulation(reps=2, region=eg.region, design=transects, pop=pop.desc, det=detect,
                        ddf.analyses.list=make.ddf.analysis.list())

survey.design <- create.survey.results(fred, dht.tables = TRUE)

my.survey <- data.for.distance(object = survey.design)
scatter.smooth(my.survey$distance, my.survey$size)
summary(my.survey$size)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   5.00   10.00   12.00   11.96   14.00   19.00 
```

![Screenshot 2019-08-14 at 12 34 21](https://user-images.githubusercontent.com/1295691/63018080-e5696080-be8f-11e9-8e92-bb8a3448987f.png)

**Comment by LHMarshall** [comment]
@erex I also took your example and repeated the data generation many times extracting the mean cluster size each time.

```
> mean.cs <- numeric(0)
> for(i in 1:100){
+     survey.design <- create.survey.results(fred, dht.tables = TRUE)
+     my.survey <- data.for.distance(object = survey.design)
+     mean.cs[i] <- summary(my.survey$size)[['Mean']]  
+ }
> hist(mean.cs)
> abline(v = 10, col = 2, lty = 2, lwd= 3)
```
![Screenshot 2019-08-14 at 12 42 00](https://user-images.githubusercontent.com/1295691/63018514-f36bb100-be90-11e9-989a-72c5a640097c.png)

**Comment by erex** [comment]
Thanks for that Laura.  At least it is possible to induce the effect, but wild to need a detection function almost without a shoulder and confidence intervals amazingly wide to get much movement out of mean group size.
![image](https://user-images.githubusercontent.com/330744/63018599-28780380-be91-11e9-8156-b04688f05023.png)

Small groups need to be invisible beyond 10 units and large groups perfectly detectable to the truncation distance.

**Comment by LHMarshall** [comment]
@erex I think the parameters have to be extreme here due to the distribution of the group size values. I think groups of dolphins are more likely to be 100+ so more variable meaning smaller differences in parameters would be required to see the same level of size bias.

![Screenshot 2019-08-14 at 12 48 11](https://user-images.githubusercontent.com/1295691/63018941-f87d3000-be91-11e9-9cd1-7c4ee52478f6.png)

**Comment by erex** [comment]
@LHMarshall 

I'm anticipating questions arising in next week's workshop about the replacement of size bias regression by size as a covariate; hence the questions this morning.

I've adjusted the scenario based upon your suggestion about group size variation being too small in my original scenario.  

The new scenario uses cluster size as log-normally distributed; producing large variation in group size, such that the sample mean is not a good approximation of the population mean as you argued this lunchtime.
```
covariate.list$size <- list(list("lognormal", list(meanlog = log(25), sdlog = log(4))))
```

This brings me to a new challenge with `DSsim`.  I won't convince anybody of the value of a group size covariate with this simulation result

```
Region:  region
No. Repetitions:  500
No. Excluded Repetitions:  0
Using only repetitions where all models converged.

Design:  Systematic Parallel Line Transect
   design.axis  =  0
   spacing  =  100

Population Detectability Summary:
    key.function  =  hn
    scale.param  =  10
    truncation  =  80

Covariate Detectability Summary (params on log scale):
   size parameters: 
Strata region 
         0.05 

Analysis Summary:
   Candidate Models:
      Model  1 :  ~ cds(key = "hn", formula = ~log(size))  was selected  500  time(s).
   criteria  =  AIC
   truncation  =  80

Summary for Individuals

Summary Statistics

  mean.Cover.Area mean.Effort   mean.n  mean.ER mean.se.ER sd.mean.ER
1         1600000       10000 19045.25 1.904525  0.2707362  0.3818939
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Estimates of Abundance (N)

  Truth mean.Estimate percent.bias    RMSE CI.coverage.prob mean.se sd.of.means
1  5000      13748.95       174.98 9071.37                0 1843.84     2399.41
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Estimates of Density (D)

  Truth mean.Estimate percent.bias        RMSE CI.coverage.prob     mean.se sd.of.means
1 0.005    0.01374895     174.9789 0.009071367                0 0.001843844  0.00239941
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Performance of the estimator of N(individuals) is based upon the number of simulated groups multiplied by the *expected* mean group size: in this case 200*25.  But with large variability in group size, the realised N(individuals) for any replicate can be quite different from 5000.

Any way to cause the N(individuals) performance reflect the actual number of individuals in each simulation replicate?

**Comment by LHMarshall** [comment]
@erex just tested for larger group size and still as most of the group sizes are close to the mean you still need fairly large differences in detection functions for there to be significant bias.

What the dashed lines in the detection function plot tells you are close to the extremes of the detection functions for the range of cluster size values. The lower line corresponds to a cluster size value of the 2.5% percentile and the upper dashed line is the detection function for the 97.5% percentile cluster size value. But as most of the cluster size values are closer to the mean then most observations will be more like the solid line. 

I generated a wee extreme example where cluster sizes were either 3 or 17 (couldn't take values inbetween). There was a 0.45 probability of seeing a cluster of size 3 and a 0.55 probability of seeing a group of 17. These probabilities are equivalent to the area under the scaled detection function. 

```
x2 <- c(3,17)
means <- unlist(lapply(as.list(1:100), FUN = function(x, x2)mean(sample(x2, 100,
  prob = c(0.45, 0.55), replace = TRUE)), x2 = x2))

> mean(means)
[1] 10.7798
```
The true mean is 10 but the mean of the means is only 10.7798 and that is where we are only choosing cluster sizes of 3 or 17. If we are choosing from a distribution where most observations are closer to the mean then it seems to make sense that we will need very significant differences in areas under the detection function for the extreme cluster size values to see substantial bias.

![Screenshot 2019-08-14 at 15 25 23](https://user-images.githubusercontent.com/1295691/63029395-66cced00-bea8-11e9-85c7-efc03f9d8d9d.png)

**Comment by LHMarshall** [comment]
@erex  Can you please send me the code for the simulation you ran above so I can take a look.. can't figure out why the bias is so high from what you posted. Thanks

**Comment by erex** [comment]
```
library(DSsim)
library(Distance)
set.seed(2232)
eg.region <- make.region()
covariate.list <- list()
# covariate.list$size <- list(list("ztruncpois", list(mean = 10)))
covariate.list$size <- list(list("lognormal", list(meanlog = log(25), sdlog = log(4))))
pop.desc <- make.population.description(covariates = covariate.list, N=200)
cov.params <- list(size = c(0.05))
detect <- make.detectability(scale.param = 10, 
                             cov.param = cov.params, 
                             truncation = 80)
plot(detect, pop.desc)
bob <- generate.population(pop.desc, detect, eg.region)

transects <- make.design()
simulation <- make.simulation()
thelines <- generate.transects(simulation)

fred <- make.simulation(reps=500, region=eg.region, design=transects, pop=pop.desc, det=detect,
                        ddf.analyses.list=make.ddf.analysis.list(dsmodel=list(~cds(key="hn", formula=~log(size))),truncation=80))

summary(run(fred))
```

**Comment by LHMarshall** [comment]
@erex ok you just found a bug! I wrongly used 25 as the mean cluster size in DSsim when it should be exp(meanlog + 0.5 * sdlog^2) so infact truth should be 13,070 NOT 5000! So your simulation actally performs ok with its estimate of 13748.95... I will fix this.

```
> meanlog <- log(25)
> sdlog <- log (4)
> exp(meanlog + 0.5 * sdlog^2)
[1] 65.3516
> 65.3516*200
[1] 13070.32
```

**Comment by erex** [comment]
happy to help; I had trouble finding much in the documentation about any of the distributions implemented.

**Comment by LHMarshall** [comment]
@erex Hmm turns out I had the expected cluster size down as the median and not the mean for all distributions... oops! That is fixed now on github

**Comment by LHMarshall** [comment]
Closing this I have made a note to do the same testing on dsims
